spring:
   application:
     name: forwarder
   profiles: 
    active: dev
   jackson:
    serialization:
      indent-output: true
   data:
    mongodb:
      uri: mongodb://localhost:27017/unreaded
kafka:
  bootstrap-servers: localhost:29092
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group.id: producer-api
    auto.offset.reset: earliest
server:
  port: 8089
logging:
  level:
    ROOT: INFO