spring:
   application:
     name: forwarder
   profiles: 
    active: dev
   jackson:
    serialization:
      indent-output: true
swagger:
    default-include-pattern: /api/.*
    title: Forward Message Service
    description:  Forward Message Service documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
kafka:
  bootstrap-servers: localhost:29092
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group.id: producer-api
    auto.offset.reset: earliest
server:
  port: 8089
logging:
  level:
    ROOT: DEBUG